### ISSUE TITLE
Downloading dataset Error 

### ISSUE THREAD

**Issue by n-hafidi** [Masseeh/DCAug#2]
Unfortunately another error while loading the dataset : 

Traceback (most recent call last):
  File "C:\Users\user\anaconda\envs\DcAug\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\anaconda\envs\DcAug\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\anaconda\envs\DcAug\DCAug-main\domainbed\scripts\download.py", line 272, in <module>
    download_vlcs(args.data_dir)
  File "C:\Users\user\anaconda\envs\DcAug\DCAug-main\domainbed\scripts\download.py", line 99, in download_vlcs
    download_and_extract(
  File "C:\Users\user\anaconda\envs\DcAug\DCAug-main\domainbed\scripts\download.py", line 28, in download_and_extract
    gdown.download(url, dst, quiet=False)
  File "C:\Users\user\anaconda\envs\DcAug\lib\site-packages\gdown\download.py", line 110, in download
    res = sess.get(url, stream=True)
  File "C:\Users\user\anaconda\envs\DcAug\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\user\anaconda\envs\DcAug\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\user\anaconda\envs\DcAug\lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\user\anaconda\envs\DcAug\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\user\anaconda\envs\DcAug\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

**Comment by shenaoqi123** [comment]
Hello, have you successfully reproduced the code of this paper?

**Comment by n-hafidi** [comment]
> Hello, have you successfully reproduced the code of this paper?

No

**Comment by shenaoqi123** [comment]
Hello, have you encountered this situation?  RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [96, 2, 3, 224, 224]

**Comment by Masseeh** [comment]
Hi, thank you for your interest in the project!
By default, the dataloader generates two augmentations per sample, making the tensors 4D rather than 3D. For example:

https://github.com/Masseeh/DCAug/blob/520367a3743f91e6ed10be3682c989005da0d1b5/domainbed/algorithms/algorithms.py#L254

This augmentation setup is currently implemented only for the ERMDAdv and ERMAdv algorithms. If you're using other algorithms, you'll need to modify the code accordingly.

**Comment by shenaoqi123** [comment]
Thank you for sharing the project. I really appreciate your explanation. I will try it again now.
